services:
  json_model_converter:
    class: PHPModelGenerator\Bundle\ParamConverter\JSONModelConverter
    tags:
      - { name: request.param_converter, priority: 0, converter: json_model_converter }
